hwdb:
  - hwdb.d/**/*
units:
  - units/**/*
documentation:
  - NEWS
  - man/*
  - docs/*
network:
  - src/libsystemd-network/**/*
  - src/network/**/*
udev:
  - src/udev/**/*
  - src/libudev/*
meson:
  - '**/meson.build'
  - meson_option.txt
busctl:
  - src/busctl/*
systemctl: 
  - src/systemctl/*
journal:
  - src/journal/*
journal-remote:
  - src/journal-remote/*
